field: 45627019-164f-4db3-a16b-ad32aed2959c
fieldLayouts:
  187b1382-7101-49a5-ae29-9c6264049343:
    tabs:
      -
        elements:
          -
            fieldUid: 3fe037c2-8647-40f2-98a9-e54e9d50d4fd
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 485c200c-515e-441a-abdc-7a7b17fc2419
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  3fe037c2-8647-40f2-98a9-e54e9d50d4fd:
    contentColumnType: text
    fieldGroup: null
    handle: medSosName
    instructions: ''
    name: 'Media Social Name'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: ''
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  485c200c-515e-441a-abdc-7a7b17fc2419:
    contentColumnType: string(255)
    fieldGroup: null
    handle: urlMedsos
    instructions: ''
    name: 'URL Medsos'
    searchable: false
    settings:
      maxLength: '255'
      placeholder: null
      types:
        - url
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Url
handle: medsos
name: Medsos
sortOrder: 1
